module.exports = {
    browser: (height = '1280', width = '800'),
    sef_url: 'https://qa-sef1.pipl.com/',
    login_button: '//*[@id="login_button"]',
    login_button_login_form: '//*[@id="submit-id-login"]',
    search_button: '//*[@id="js-navbar"]/ul/li[1]/div',
    valid_email: 'shelly.shir@pipl.com',
    email_without_domain: 'shelly.shir@com',
    invalid_email: 'shelly.shir$@pipl.com',
    click_second_search_button: '//*[@id="js-navbar"]/ul/li[1]/ul/li[1]/a/span',
    click_api_in_search_menu: '//*[@id="js-navbar"]/ul/li[1]/ul/li[2]/a',
    click_files_in_search_menu: '//*[@id="js-navbar"]/ul/li[1]/ul/li[3]/a',
    click_request_a_demo_button: '/html/body/div[1]/div/section[1]/button',
    click_get_started_button: '/html/body/div/div/div/div/section/div/div[@class=\'c-slider-area-buttons\']/button[@class=\'btn btn-lg btn-blue\']',
    click_close_button: '//button[@class=\'pull-right close-btn btn btn-lg btn-link\']',
    api_start_for_free_button: '//*[@id="js-homepage-top-signup"]',
    api_start_for_free_green_button: '//a[@id=\'js-homepage-bottom-signup\']',
    api_start_my_free_trail_pricing_page: '//div[@class=\'o-plans-cards\']/a[@id=\'js-signup-button\']',
    click_create_my_account_button: '/html/body[@class=\'en modal-open\']/div[5]/div/div[@class=\'form-modal fade in modal\']/div[@class=\'modal-lg modal-dialog\']/div[@class=\'modal-content\']/div[@class=\'modal-footer\']/button[@class=\'pull-left btn btn-lg btn-primary\']',
    click_yes_choose_teams_tool: '//div[1]/label',
    click_no_choose_teams_tool: '//div[2]/label',
    click_accept_terms: '//div[@class=\'col-sm-6 col-xs-12\'][1]/div/form/div/div/div[@class=\'checkbox undefined\']/label',
    click_select_exp_month: '/html/body/div[5]/div/div[2]/div/div/div[2]/div/div[1]/div/div/form/div[3]/div[1]/div/select',
    select_exp_month: '/html/body/div[5]/div/div[2]/div/div/div[2]/div/div[1]/div/div/form/div[3]/div[1]/div/select/option[7]',
    click_select_exp_year: '/html/body/div[5]/div/div[2]/div/div/div[2]/div/div[1]/div/div/form/div[3]/div[2]/div/select',
    select_exp_year: '/html/body/div[5]/div/div[2]/div/div/div[2]/div/div[1]/div/div/form/div[3]/div[2]/div/select/option[11]',
    click_select_country: '/html/body/div[5]/div/div[2]/div/div/div[2]/div/div[1]/div/div/form/div[5]/div[1]/div/select',
    select_country_with_state: '/html/body/div[5]/div/div[2]/div/div/div[2]/div/div[1]/div/div/form/div[5]/div[1]/div/select/option[237]',
    click_select_state: '/html/body/div[5]/div/div[2]/div/div/div[2]/div/div[1]/div/div/form/div[5]/div[2]/div/select',
    select_state: '/html/body/div[5]/div/div[2]/div/div/div[2]/div/div[1]/div/div/form/div[5]/div[2]/div/select/option[13]',
    select_unlimited_searches_pro: '/html//div[@class=\'modal-content\']//div[@class=\'row\']//div[@class=\'c-checkout-payment__explanation\']//div[@class=\'rc-slider-mark\']/span[@class=\'rc-slider-mark-text\']/div[@class=\'slider-text\']',
    select_unlimited_searches_in_search_page: '//span[@class=\'rc-slider-mark-text\']/div[@class=\'slider-text\']',
    select_200_searches_pro: '//span[@class=\'rc-slider-mark-text rc-slider-mark-text-active\']/div[@class=\'slider-text\']',
    select_200_searches_pro_in_search_page: '//span[@class=\'rc-slider-mark-text rc-slider-mark-text-active\'][1]/div[@class=\'slider-text\']',
    select_500_searches_pro_in_search_page: '//div[@class=\'rc-slider-mark\']/span[@class=\'rc-slider-mark-text rc-slider-mark-text-active\'][2]/div[@class=\'slider-text\']',
    select_unlimited_searches_pro_in_search_page: '//div[@class=\'rc-slider-mark\']/span[@class=\'rc-slider-mark-text\']/div[@class=\'slider-text\']',
    select_yearly_subscription: '//div[@class=\'c-checkout-payment__period\']/div[@class=\'radio c-radio-blue-button\'][1]/label',
    select_monthly_subscription: '//div[@class=\'c-checkout-payment__period\']/div[@class=\'radio c-radio-blue-button\'][2]/label',
    continue_with_the_free_version_button: '//div[@class=\'c-slider-area-buttons\']/a[@class=\'btn btn-link\']',
    remember_me_checkbox: '//div[@class=\'form-group\'][2]/input[@id=\'id_password\']',
    forgot_password_login_page: '//div[@class=\'checkbox\']/a[@id=\'reset-password\']/small',
    click_sign_out_user_menu: '//*[@id="logout_link"]',
    click_add_subscription_in_sub_page: '//div[@class=\'modal-footer\']/button[@class=\'pull-left btn btn-lg btn-primary\']',
    assign_subscription_to_new_user: '//div[@class=\'assign-new-user\']/div[@class=\'radio c-radio-blue-button\']/label',
    input_full_name_assign_subscription_to_new_user: '//input[@placeholder=\'User full name\']',
    input_email_assign_subscription_to_new_user: '//input[@placeholder=\'invitation will be sent here\']',
    input_password_assign_subscription_to_new_user: '//input[@placeholder=\'at least 6 characters\']',
    api_try_our_live_demo__button: '//*[@id="js-homepage-demo"]',
    api_demo_page_title: '//div[@class=\'o-demo-intro\']/h1[@class=\'ch-header\']',
    api_try_it_button_demo_page: '//*[@id="demo-form"]/div/div[12]/div[2]/button',
    api_clear_button_demo_page: '//*[@id="js-clear-demo"]',
    api_pricing_title_in_menu: '//*[@id="js-navbar"]/ul/li[4]/a',
    api_premium_data_coverage_switch_button: '//div[@class=\'bootstrap-switch-container\']/span[@class=\'bootstrap-switch-label\']',
    api_contact_title_in_menu: '//li[@class=\'ch-item  is-selected\']/a',
    files_get_started_button: '//a[@class=\'btn-blue inverted transapernt btn btn-lg s-btn-pipl\']',
    files_get_started_button_end_of_page: '//a[@class=\'btn btn-blue btn-lg s-btn-pipl s-m-b-40\']',
    files_drop_your_files_here: '//div[@class=\'c-file-list__empty col-xs-12\']/p[@class=\'c-file-list__empty-text\']',
    files_upload_file_button: '//*[@id="main-content"]/div/div[1]/div[1]/div[2]/div/button',
    files_get_the_walk_through_button: '//*[@id="js-video-walk"]',
    files_the_walk_through_video: '//div[@class=\'c-header-hp-btn\']/a[@id=\'js-video-walk\']',
    files_uploads_title_in_menu: '//*[@id="js-navbar"]/ul/li[2]/a',
    files_pricing_title_in_menu: '//*[@id="js-navbar"]/ul/li[3]/a',
    files_contact_title_in_menu: '//*[@id="js-navbar"]/ul/li[4]/a',


    advanced_search_page_title_please_enter_all_names_adress: '//div[@class=\'row\']/div[@class=\'col-xs-12 col-md-9 \']/div[@class=\'o-advanced\']/p',
    advanced_search_page_search_button: '//button[@class=\'btn btn-md btn-blue\']',
    advanced_search_button_on_search_page: '//form[@id=\'advanced_search_form\']/div[@class=\'c-pro-tools\']/a[@class=\'icon-advanced\']',
    advanced_search_edit_button_on_search_page: '//div[@id=\'advanced_search\']/div[@class=\'head hidden-xs hidden-sm\']/a[@class=\'js-init-edit-advanced\']',
    advanced_search_more_options_button_search_by_menu: '//div[@class=\'deepnc group\']/a[@class=\'more more-advanced hidden-xs hidden-sm\']',
    advanced_search_error_mandatory_fields: '//div[@class=\'o-advanced\']//div[@class=\'form-group has-error\']/span[@class=\'help-block\']',
    advanced_search_form_errors: '//div[@class=\'form-group has-error\']/span[@class=\'help-block\']',
    advanced_search_form_errors_in_top_of_page: '//div[@class=\'row\']/div[@class=\'col-xs-12 col-md-9 \']/div[@class=\'o-advanced\']/div[@class=\'alert alert-danger\']',
    input_fn_1_advanced_search_form: '//div[@class=\'field-wrapper row\'][1]/div[@class=\'col-sm-10 col-xs-12\']/div[@class=\'row\'][1]/div[@class=\'col-sm-9 col-xs-12\']//div[@class=\'row\']/div[@class=\'col-sm-4 col-xs-12\'][1]/input[@id=\'formInlineName\']',
    input_fn_2_advanced_search_form: '//div[@class=\'field-wrapper row\'][1]/div[@class=\'col-sm-10 col-xs-12\']/div[@class=\'row\'][2]/div[@class=\'col-sm-9 col-xs-12\']/div[@class=\'form-group\']/div[@class=\'row\']/div[@class=\'col-sm-4 col-xs-12\'][1]/input[@id=\'formInlineName\']',
    input_mn_1_advanced_search_form: '//div[@class=\'field-wrapper row\'][1]/div[@class=\'col-sm-10 col-xs-12\']/div[@class=\'row\'][1]/div[@class=\'col-sm-9 col-xs-12\']//div[@class=\'row\']/div[@class=\'col-sm-4 col-xs-12\'][2]/input[@id=\'formInlineName\']',
    input_mn_2_advanced_search_form: '//div[@class=\'field-wrapper row\'][1]/div[@class=\'col-sm-10 col-xs-12\']/div[@class=\'row\'][2]/div[@class=\'col-sm-9 col-xs-12\']/div[@class=\'form-group\']/div[@class=\'row\']/div[@class=\'col-sm-4 col-xs-12\'][2]/input[@id=\'formInlineName\']',
    input_ln_1_advanced_search_form: '//div[@class=\'field-wrapper row\'][1]/div[@class=\'col-sm-10 col-xs-12\']/div[@class=\'row\'][1]/div[@class=\'col-sm-9 col-xs-12\']//div[@class=\'row\']/div[@class=\'col-sm-4 col-xs-12\'][3]/input[@id=\'formInlineName\']',
    input_ln_2_advanced_search_form: '//div[@class=\'field-wrapper row\'][1]/div[@class=\'col-sm-10 col-xs-12\']/div[@class=\'row\'][2]/div[@class=\'col-sm-9 col-xs-12\']/div[@class=\'form-group\']/div[@class=\'row\']/div[@class=\'col-sm-4 col-xs-12\'][3]/input[@id=\'formInlineName\']',
    add_another_name_button: '//div[@class=\'field-wrapper row\'][1]/div[@class=\'col-sm-10 col-xs-12\']/div[@class=\'row\']/div[@class=\'action o-advanced-field col-sm-3 col-xs-12\']/a[@class=\'text-success\']/small',
    input_emails_1_advanced_search_form: '//div[@class=\'field-wrapper row\'][2]/div[@class=\'col-sm-10 col-xs-12\']/div[@class=\'row\']/div[@class=\'col-sm-9 col-xs-12\']//div[@class=\'row\']/div[@class=\'col-xs-12\']/input[@class=\'form-control\']',
    input_emails_2_advanced_search_form: '//div[@class=\'field-wrapper row\'][2]/div[@class=\'col-sm-10 col-xs-12\']/div[@class=\'row\'][2]/div[@class=\'col-sm-9 col-xs-12\']/div[@class=\'form-group\']/div[@class=\'row\']/div[@class=\'col-xs-12\']/input[@class=\'form-control\']',
    add_another_email_button: '//div[@class=\'field-wrapper row\'][2]/div[@class=\'col-sm-10 col-xs-12\']/div[@class=\'row\']/div[@class=\'action o-advanced-field col-sm-3 col-xs-12\']/a[@class=\'text-success\']/small',
    input_phones_1_country_code_advanced_search_form: '//div[@class=\'field-wrapper row\'][3]/div[@class=\'col-sm-10 col-xs-12\']/div[@class=\'row\']/div[@class=\'col-sm-9 col-xs-12\']//div[@class=\'row\']/div[@class=\'col-sm-4 col-xs-12\']/input[@id=\'formInlineName\']',
    input_phones_1_phone_advanced_search_form: '//div[@class=\'field-wrapper row\'][3]/div[@class=\'col-sm-10 col-xs-12\']/div[@class=\'row\']/div[@class=\'col-sm-9 col-xs-12\']//div[@class=\'row\']/div[@class=\'col-sm-8 col-xs-12\']/input[@id=\'formInlineName\']',
    input_phones_2_country_code_advanced_search_form: '//div[@class=\'field-wrapper row\'][3]/div[@class=\'col-sm-10 col-xs-12\']/div[@class=\'row\'][2]/div[@class=\'col-sm-9 col-xs-12\']/div[@class=\'form-group\']/div[@class=\'row\']/div[@class=\'col-sm-4 col-xs-12\']/input[@id=\'formInlineName\']',
    input_phones_2_phone_advanced_search_form: '//div[@class=\'field-wrapper row\'][3]/div[@class=\'col-sm-10 col-xs-12\']/div[@class=\'row\'][2]/div[@class=\'col-sm-9 col-xs-12\']/div[@class=\'form-group\']/div[@class=\'row\']/div[@class=\'col-sm-8 col-xs-12\']/input[@id=\'formInlineName\']',
    add_another_phone_button: '//div[@class=\'field-wrapper row\'][3]/div[@class=\'col-sm-10 col-xs-12\']/div[@class=\'row\']/div[@class=\'action o-advanced-field col-sm-3 col-xs-12\']/a[@class=\'text-success\']/small',
    input_address_house_advanced_search_form: '//div[@class=\'form-group\']/div[@class=\'row\']/div[@class=\'o-advanced-field col-sm-3 col-xs-6\'][1]/input[@id=\'formInlineName\']',
    input_address_street_advanced_search_form: '//div[@class=\'col-sm-9 col-xs-12\']/div[@class=\'form-group\']/div[@class=\'row\']/div[@class=\'o-advanced-field col-sm-3 col-xs-6\'][2]/input[@id=\'formInlineName\']',
    input_address_city_advanced_search_form: '//form[@class=\'o-advanced-form \']/div[@class=\'field-wrapper row\'][5]/div[@class=\'col-sm-10 col-xs-12\']/div[@class=\'row\']/div[@class=\'col-sm-9 col-xs-12\']/div[@class=\'form-group\']/div[@class=\'row\']/div[@class=\'o-advanced-field col-sm-6 col-xs-12\']/div[@class=\'Select select-location is-clearable is-searchable Select--single\']/div[@class=\'Select-control\']/span[@id=\'react-select-2--value\']/div[@class=\'Select-placeholder\']',
    add_another_address_button: '//div[@class=\'field-wrapper row\'][5]/div[@class=\'col-sm-10 col-xs-12\']/div[@class=\'row\']/div[@class=\'action o-advanced-field col-sm-3 col-xs-12\']/a[@class=\'text-success\']/small',
    input_jobs_1_organization_advanced_search_form: '//input[@name=\'org\']',
    input_jobs_1_job_title_advanced_search_form: '//input[@name=\'title\']',
    input_jobs_2_organization_advanced_search_form: '//div[@class=\'field-wrapper row\'][8]/div[@class=\'col-sm-10 col-xs-12\']/div[@class=\'row\'][2]/div[@class=\'col-sm-9 col-xs-12\']/div[@class=\'form-group\']/div[@class=\'row\']/div[@class=\'col-sm-6 col-xs-12\'][1]/input[@id=\'formInlineName\']',
    input_jobs_2_job_title_advanced_search_form: '//div[@class=\'field-wrapper row\'][8]/div[@class=\'col-sm-10 col-xs-12\']/div[@class=\'row\'][2]/div[@class=\'col-sm-9 col-xs-12\']/div[@class=\'form-group\']/div[@class=\'row\']/div[@class=\'col-sm-6 col-xs-12\'][2]/input[@id=\'formInlineName\']',
    add_another_job_button: '//div[@class=\'field-wrapper row\'][8]/div[@class=\'col-sm-10 col-xs-12\']/div[@class=\'row\']/div[@class=\'action o-advanced-field col-sm-3 col-xs-12\']/a[@class=\'text-success\']/small',
    input_associates_1_fn_advanced_search_form: '//input[@name=\'rel_fn\']',
    input_associates_1_ln_advanced_search_form: '//input[@name=\'rel_ln\']',
    input_associates_2_fn_advanced_search_form: '//div[@class=\'field-wrapper row\'][6]/div[@class=\'col-sm-10 col-xs-12\']/div[@class=\'row\'][2]/div[@class=\'col-sm-9 col-xs-12\']/div[@class=\'form-group\']/div[@class=\'row\']/div[@class=\'col-sm-4 col-xs-12\'][1]/input[@id=\'formInlineName\']',
    input_associates_2_ln_advanced_search_form: '//*[@id="root"]/div/section/div/div/div/form/div/div/div[2]/div[1]/div/div/div[3]',
    input_associates_3_fn_advanced_search_form: '//div[@class=\'field-wrapper row\'][6]/div[@class=\'col-sm-10 col-xs-12\']/div[@class=\'row\'][3]/div[@class=\'col-sm-9 col-xs-12\']/div[@class=\'form-group\']/div[@class=\'row\']/div[@class=\'col-sm-4 col-xs-12\'][1]/input[@id=\'formInlineName\']',
    input_associates_3_ln_advanced_search_form: '//*[@id="root"]/div/section/div/div[2]/div/form/div[6]/div[2]/div[3]/div[1]/div/div/div[3]',
    add_another_associates: '//div[@class=\'field-wrapper row\'][6]/div[@class=\'col-sm-10 col-xs-12\']/div[@class=\'row\']/div[@class=\'action o-advanced-field col-sm-3 col-xs-12\']/a[@class=\'text-success\']/small',
    input_education_1_school_advanced_search_form: '//input[@placeholder=\'School\']',
    input_education_1_academic_degree_advanced_search_form: '//input[@placeholder=\'Academic Degree\']',
    input_education_2_school_advanced_search_form: '//div[@class=\'field-wrapper row\'][7]/div[@class=\'col-sm-10 col-xs-12\']/div[@class=\'row\'][2]/div[@class=\'col-sm-9 col-xs-12\']/div[@class=\'form-group\']/div[@class=\'row\']/div[@class=\'col-sm-6 col-xs-12\'][1]/input[@id=\'formInlineName\']',
    input_education_2_academic_degree_advanced_search_form: '//*[@id="root"]/div/section/div/div[2]/div/form/div[7]/div[2]/div[2]/div[1]/div/div/div[2]',
    add_another_education_button: '//div[@class=\'field-wrapper row\'][7]/div[@class=\'col-sm-10 col-xs-12\']/div[@class=\'row\']/div[@class=\'action o-advanced-field col-sm-3 col-xs-12\']/a[@class=\'text-success\']/small',
    input_usernames_advanced_search_form: '//input[@name=\'un\']',
    input_usernames_2_advanced_search_form: '//div[@class=\'field-wrapper row\'][4]/div[@class=\'col-sm-10 col-xs-12\']/div[@class=\'row\'][2]/div[@class=\'col-sm-9 col-xs-12\']/div[@class=\'form-group\']/div[@class=\'row\']/div[@class=\'col-xs-12\']/input[@id=\'formInlineName\']',
    add_another_username: '//div[@class=\'field-wrapper row\'][4]/div[@class=\'col-sm-10 col-xs-12\']/div[@class=\'row\']/div[@class=\'action o-advanced-field col-sm-3 col-xs-12\']/a[@class=\'text-success\']/small',
    input_age_advanced_search_form: '//*[@id="formInlineAge"]',



    validation_request_a_demo_button: '/html/body/div[1]/div/section[1]/button',
    validation_enter_promo_code_button: '//a[@class=\'btn-link btn-lg\']',
    validation_get_started_button: '//*[@id="root"]/div/section/div[2]/div[2]/button',
    validation_start_searching_like_pro_button: '/html/body/div[6]/div/div[2]/div/div/div[3]/a',
    validation_invoice_button: '/html/body/div[6]/div/div[2]/div/div/div[3]/span/a',
    validation_finished_icon: '/html/body/div[5]/div/div/div/div/div/div[@class=\'row\']/div[@class=\'col-sm-12 col-xs-12\']/div[@class=\'c-finished\']/div[@class=\'c-finished-icon\']',
    validation_youre_a_pro_icon: '/html/body/script[16]',
    pipl_icon_search_page: '/html/body/section[1]/div/div/div[1]/img',
    pipl_icon_in_login_page: '/html/body/section/div[1]/div/a/img',
    pipl_icon_files_homepage: '/html/body/header/nav/div/div/div[1]/a/img',
    linkedin_icon: '//img[@src=\'/favicons/55.png\']',
    twitter_icon: '//*[@id="unique_profile_records"]/div[3]/div[2]/div[3]/img',
    white_pages_icon: '//*[@id="unique_profile_records"]/div[6]/div[2]/div[3]/img',
    facebook_icon: '//img[@src=\'/favicons/39830.png\']',
    google_icon: '//*[@id="unique_profile_records"]/div[4]/div[2]/div[3]/img',
    phone_icon_in_summary: '//*[@id="profile_container_middle"]/div[3]/div[1]/span',
    email_icon_in_summary: '//*[@id="profile_container_middle"]/div[6]/div[1]/span',
    associated_with_icon_in_summary: '//img[contains(@src,"/static/img/icons/icon_associates_gray.png")]',
    additional_names_icon_in_summary: '//*[@id="profile_container_middle"]/div[2]/div[1]/img',
    usernames_icon_in_summary: '//img[contains(@src,"/static/img/icons/icon_usernames_gray.png")]',
    results_for_icons_in_person_page: '/html/body[@class=\' en\']/div[@class=\'o-main\']/div[@id=\'sidebar\']',
    name_email_username_or_phone_field: '/html/body/section[1]/div/div/div/form/div[@class=\'search-form__inputs\']/span[@class=\'search-form__query\']/input[@id=\'findall\']',
    search_field_in_person_page: '//*[@id="findall"]',
    location_field_in_person_page: '//*[@id="findlocation"]',
    address_in_person_page: '//*[@id="profile_container_middle"]/div[4]/div[2]/ul[1]/li[1]/a',
    address_of_maurice_in_person_page: '//*[@id="profile_container_middle"]/div[1]/div[2]/ul[1]/li[1]/a/span',
    career_in_person_page: '//*[@id="profile_container_middle"]/div[1]/div[2]/ul/li/span',
    gender_in_summary_in_person_page: '//*[@id="profile_summary"]/ul/li[1]',
    map_of_kevin_kelber_address: '//*[@id="profile_container_middle"]/div[4]/div[2]/ul[1]/li[2]/a/img',
    map_of_maurice_faucher_address: '//*[@id="profile_container_middle"]/div[1]/div[2]/ul[1]/li[2]/a/img',
    map_phone_information_in_person_page: '//*[@id="phone_information"]/div[2]/div[1]/a/img',
    phone_of_kevin_kelber: '//*[@id="profile_container_middle"]/div[3]/div[2]/ul/li/a[1]',
    phones_paragraph_in_mstch_result_page: '//div[@id=\'profile_container\']/div[@id=\'profile_container_middle\']/div[@class=\'row-line group\']/div[@class=\'values\']/ul[@class=\'phones\']',

    Location_field: '//*[@id="findlocation"]',
    search_by_field_fn: '//*[@id="fn"]',
    search_by_field_mn: '//*[@id="mn"]',
    search_by_field_ln: '//*[@id="ln"]',
    search_by_field_email: '//input[@id=\'em\']',
    search_by_field_phone: '//*[@id="phn"]',
    search_by_field_username: '//input[@id=\'un\']',
    search_by_field_location: '//*[@id="filter-add-loc"]',
    search_by_field_job_title: '//*[@id="title"]',
    check_box_location_virginia: '//*[@id="filter-loc"]/li[1]/label/input[1]',
    check_box_31_to_40_ages: '//input[contains(@value,"30|40")]',
    check_box_41_to_50_ages: '//*[@id="filter-age"]/li[4]/label/span',

    api_email_field_in_demo_page: '//input[@class=\'form-control s-icon-email\']',
    contact_page_name_field: '//*[@id="id_name"]',
    contact_page_email_field: '//*[@id="id_email"]',
    contact_page_subject_field: '//*[@id="id_subject"]',
    contact_page_issue_list: '//*[@id="id_issue"]',
    contact_page_issue_technical_support: '//*[@id="id_issue"]/option[3]',
    contact_page_message_field: '//*[@id="id_message"]',
    contact_page_contact_us_button: '//*[@id="js-contact-form"]/div/div[2]/div[4]/button',


    results_for_multi_person_free_search: '/html/body[@class=\' en\']//div[@id=\'match_results\']/div[@class=\'title-header\']',
    results_for_multi_person_pro:'//*[@id="match_results"]/div[1]/span',
    results_for_single_person: '//*[@id="advanced_search"]/div[1]',
    results_for_no_results: '/html/body[@class=\' en\']/div[@class=\'o-main\']/div[@id=\'main_content\']/div[@id=\'match_results\']/div[@class=\'title-header no_results\']',
    results_for_person_search_pointer:'//*[@id="advanced_search"]/div[2]/div[1]/div/div/div',
    result_for_the_searched_name: '/html/body[@class=\' en\']/div[@class=\'o-main\']/div[@id=\'sidebar\']/form/div/div/div/div[@class=\'item group\'][1]/div[@class=\'text\']',
    result_for_education: '//*[@id="advanced_search"]/div[2]/div[1]/div[4]/div',
    more_option_of_search_by: '//*[@id="advanced_fields"]/div[8]/a[1]',
    all_ages_of_search_by: '/html//ul[@id=\'filter-age\']/li[@id=\'filter-age-all\']/label[@class=\'all selectbox-styled\']/span',
    all_locations_of_search_by: '//*[@id="filter-loc-all"]/label/span',
    israel_in_search_by_locations: '//*[@id="filter-loc"]/li[3]/label/span',
    brazil_in_search_by_locations: '//*[@id="filter-loc"]/li[4]/label/span',
    text_valid_possibly_related_results: '//*[@id="no_match_results"]/div[1]',
    first_result_of_search: '/html/body[@class=\' en\']/div[@class=\'o-main\']/div[@id=\'main_content\']/div[@id=\'match_results\']/div[@class=\'content\']/div[1]/div/div[@class=\'title truncate\']/a',
    second_result_of_search: '//*[@id="match_results"]/div[2]/div[2]/div[2]/div[1]/a',

    input_full_name_req_demo: '//input[@placeholder=\'Your first & last name\']',
    input_full_name_sign_up_pro: '/html/body/div[5]/div/div[2]/div/div/div[2]/div/div[1]/div/form/div[1]/span[1]/input',
    input_name_on_card: '/html/body/div[5]/div/div[2]/div/div/div[2]/div/div[1]/div/div/form/div[1]/div/div/span[1]/input',
    input_card_number: 'input[name=cardnumber]',
    input_exp_date: 'input[name=exp-date]',
    input_email_pipl_domain_req_demo: '//input[@placeholder=\'Your email address\']',
    input_email_pipl_domain_sign_up_pro: '/html/body/div[5]/div/div[2]/div/div/div[2]/div/div[1]/div/form/div[2]/span[1]/input',
    input_decision_maker_business_email: '/html/body/div[5]/div/div[2]/div/div/div[2]/div/div/div/form/div[7]/div[2]/span[1]/input',
    input_password: '/html/body/div[5]/div/div[2]/div/div/div[2]/div/div[1]/div/form/div[3]/span[1]/input',
    input_company_name: '//input[@placeholder=\'Your company name\']',
    input_job_title: '//input[@placeholder=\'Your job title\']',
    input_decision_maker_job_title: '/html/body/div[5]/div/div[2]/div/div/div[2]/div/div/div/form/div[7]/div[3]/span[1]/input',
    input_phone_number: '//input[@placeholder=\'Your phone number\']',
    input_cvv: 'input[name=cvc]',
    input_city: '/html/body/div[5]/div/div[2]/div/div/div[2]/div/div[1]/div/div/form/div[5]/div[3]/div/span[1]/input',
    input_address: '/html/body/div[5]/div/div[2]/div/div/div[2]/div/div[1]/div/div/form/div[6]/div[1]/div/span[1]/input',
    input_postal_code: '/html/body/div[5]/div/div[2]/div/div/div[2]/div/div[1]/div/div/form/div[6]/div[2]/div/span[1]/input',
    input_pro_subscription_quantity: '/html/body[@class=\'en modal-open\']//div[@class=\'c-checkout_payment__quantity\']/div/input[@id=\'subscription_quantity\']',
    input_organization_name: '/html/body/div[5]/div/div[2]/div/div/div[2]/div/div[1]/div/div/form/div[1]/div/div/span[1]/input',
    input_website: '/html/body/div[5]/div/div[2]/div/div/div[2]/div/div[1]/div/div/form/div[3]/div/div/span/input',
    input_invoice_email: '/html/body/div[5]/div/div[2]/div/div/div[2]/div/div[1]/div/div/form/div[2]/div/div/span/input',
    input_phone_of_organization: '/html/body/div[5]/div/div[2]/div/div/div[2]/div/div[1]/div/div/form/div[4]/div/div/span/input',
    input_email_login: '//div[@class=\'form-group\'][1]/input[@id=\'id_email\']',
    input_password_login: '//div[@class=\'form-group\'][2]/input[@id=\'id_password\']',

    submit_request_a_demo: '/html/body[@class=\'en modal-open\']/div[5]/div/div[@class=\'form-modal modal-request-demo fade in modal\']/div[@class=\'modal-sm modal-dialog\']/div[@class=\'modal-content\']/div[@class=\'modal-footer\']/button[@class=\'pull-left btn btn-lg btn-primary\']',
    submit_PRO_subscription: '/html/body/div[5]/div/div[2]/div/div/div[3]/button[1]',
    text_youre_a_pro: '//div[@class=\'c-finished\']/h2',
    text_demo_request_sent: '/html//div[@class=\'modal-content\']//h4[@class=\'modal-title\']',
    text_someone_will_be_in_touch: '/html//div[@class=\'modal-content\']//div[@class=\'col-sm-12 col-xs-12\']/div[@class=\'c-finished\']/div[2]',
    text_valid_sign_up_pro_title: '//div[@class=\'modal-header\']/h4[@class=\'modal-title\']',
    text_valid_already_have_account_sign_up_modal: '/html/body/div[5]/div/div[2]/div/div/div[3]/a',
    text_valid_Search_By: '//*[@id="advanced_search"]/div[1]',
    text_valid_billing_modal_pro: '/html/body/div[5]/div/div[2]/div/div/div[2]/div/div[1]/div/div/form/div[4]/div/p',
    text_Just_one_last_thing_Well_need_your_card_details: '/html/body/div[5]/div/div[2]/div/div/div[1]/h4',
    text_Please_read_and_agree_to_the_terms_Css: '//body//div[@class=\'table-row\']/div[@class=\'tos-section\']/div/span[@class=\'help-block text-left\']',
    text_with_the_worlds_largest_people_search_phone_number: '/html/body/section[1]/div/div/div[3]/div',
    text_sorry_invalid_or_missing_error_freesearch: '//*[@id="content"]',
    text_no_result_found_for: '//*[@id="match_results"]/div[1]',
    text_suggestion_for_no_result_page: '//div[@class=\'no_results_info\']',
    text_make_sure_billing_address_associated_with_your_card: '//p[@class=\'c-credit-card-form__note\']',
    text_choose_how_many_searches_per_month: '//div[@class=\'form-modal fade in modal\']//div[@class=\'c-checkout-payment__explanation\']',
    login_email_or_password_not_correct: '/html/body/section[@class=\'container o-main\']/div[1]/div[@class=\'center-form\']/form[@id=\'login-form\']/div[@class=\'form-group text-danger\']',
    sign_up_form_errors: '//div[@class=\'form-group form-group-sm has-error\']/span[@class=\'help-block\']',
    we_will_need_valid_email_to_get_in_touch: '//div[@class=\'form-group form-group-sm has-error\'][1]/span[@class=\'help-block\']',
    request_pro_form_errors: '//div[@class=\'form-group form-group-sm has-error\']/span[@class=\'help-block\']',
    text_valid_the_search_in_profile_summary: '//div[@class=\'header\']',
    text_number_of_subscriptions_one_for_each: '/html//div[@class=\'col-sm-6 col-xs-12\'][2]/div/div[@class=\'c-checkout-payment col-xs-12\']/div[@class=\'c-checkout-payment__explanation\']',
    text_please_enter_your_organization_details: '//div[@class=\'modal-lg modal-dialog\']/div[@class=\'modal-content\']/div[@class=\'modal-header\']/h4[@class=\'modal-title\']',
    present_company_name: '/html//div[@class=\'form-group form-group-sm\'][1]/span[@class=\'input-group\']/span[@class=\'input-group-addon\']',
    user_name_in_user_menu_css: '#js-navbar > ul > li.ch-item.o-usermenu > a.hidden-xs.hidden-sm > span',
    professional_tools: '//form[@id=\'advanced_search_form\']/div[@class=\'c-pro-tools\']/h3',
    advanced_search_in_user_menu: '//ul[@class=\'o-loginuser dropdown-menu\']/li[@class=\'icon-advanced o-loginuser__item\']/a',
    subscription_in_user_menu: '//li[@class=\'icon-mysubscription o-loginuser__item\']/a',
    add_subscription_button_sub_page: '//*[@id="root"]/div/section/div/div[2]/div/h3/div/a',
    add_subscription_button_sub_page_when_assign_exist:'//*[@id="root"]/div/section/div/div[2]/div/h3/div/a[2]',
    users_email_sub_page: '//div[@class=\'o-subscription-item__user truncate\']',
    text_api_create_your_account: '//div[@class=\'modal-dialog form-modal modal-sm s-modal\']/form[@id=\'signup_form\']/div[@class=\'modal-content\']/div[@class=\'modal-header\']/h4[@class=\'modal-title\']',
    text_files_fill_blanks_in_your_customer_list:'//div[@class=\'container\']/div[@class=\'c-header-hp-wrapper\']/h1[@class=\'blue-text\']',
    text_files_getting_people_data_is_easy: '//div[@class=\'container\'][1]/h1[@class=\'blue-text text-center s-m-b-70 s-m-t-40\']',
    text_contact_thank_you_contacting_pipl: '//div[@class=\'c-contact__header\']/p[@class=\'text-detail\']',
    text_homepage: '/html/body/section[1]/div/div/div[3]/div',
    text_marketing_page: '/html/body/div[1]/div/section[1]/h1',
    text_registration_modal: '/html/body/div[5]/div/div[2]/div/div/div[1]/h4',
    pipl_icon_marketing_page: '/html/body/header/nav/div/div[1]/a/img',
    header_person_page_name: '//*[@id="profile_summary"]/div[1]',

    language_menu: '//*[@id="lang-menu"]/a',
    language_menu_spanish: '//*[@id="js-menu-options"]/li[2]/a',
    language_menu_english: '//*[@id="js-menu-options"]/li[1]/a',
    language_menu_portuguese: '//*[@id="js-menu-options"]/li[3]/a',


    search_pointer_single_match_url: 'https://qa-sef1.pipl.com/search/?sp=97845f13a749e49d9d6c2b6cf32d6716ca1c1dbfb3703f21bd93d48e4fbb9651c58cac686f168b81339e12c0586edb365472a3f2d166e962ad737705c8a0ab858b0eba68ba60cf48df7078f631434229033aa89be04a3807f9e79a399ae257eb63960a5a4d2fc6b4beb62eb6d56d091017427cc8b33af18b3576dbdabc8a7793f3a6003e7899dd57c77c254db56017357dea8d003ff9d8f7d51b9fed5bec518a2ff125416346a1a5ce379a9cff4a578148735fc2c578631cc65781c9fbcdb63fe556d2e636b509722abddd5a07318e04',
    search_pointer_multiple_person_url: 'https://qa-sef1.pipl.com/search/?sp=5611452942a2d756569e3ddaecaff587ef98aafd894e81e27b3ccef13c0d694d8db173d097fe9c327f113a04fa0c2dd15812b360aabb8b466334f0726fb2a28bcdd0ec3f9cd432510b619eb4256b40842aa5342fdd5c6f9fb9e1d22b61503fb8e18cd2b7a982663b0c9313c6d5e58cc1cb5171553021c8bee0ed3ca419edf11a98b11eaf55f9a1c25577bbd3d6fbf4c2',
    search_pointer_no_results_url:'https://qa-sef1.pipl.com/search/?sp=569d359d830a43801ec9618dcecc64308517a54429495aeb4a3cf096101e9ac1800e0a49ebff8a83615c9aed44c9d13458459801378b652b25265ea529c52775e09488e4a756ad92e7677b9945b03307e391f36e45766d96b990fd43a2009b37b1d6ba43c2b4adcd01481d4f31cb9d76c0f0b697334e2465b122961e2688d9b70a02b21ccc380c439861dc87e77617345c340d30dcf008cb205765e7d981624c',
    search_pointer_person_url: 'https://qa-sef1.pipl.com/search/?sp=931ab11a39f1a29fd9ecd70781ed07b98b1fc442310984d7c580f0a712c62256d9cca9d5df719a6420a4f9bc8db20c6bdf465bdb7d24ab94b7d440f44cc361545bca08b1ea46aefac44f3065e08e06b964f77113114cebfec2c56ef8ec4d2baca8f5ba89ad1a4944803dd6faa7ca9adf81695fdeedc7760fe9389c28eaa920cc41bc6f21d1e2f7c9156a519709d43fc50bf78a4db080d134b4ac7a1c97ef5ed37c8d0a797a47ce59f19d5484b24c15a868156d0737d5b9ed4565c8af031114eafa901e8152b28ec23e8f547b2281bbe6fa6d7db08c3e74a76a997545471b46d5f02116dad8fe3ea92a8dbf5a9a29d02684bee34ebd70c3ba670405da0c062aa015d04e15391323065b56986f0724ae8a67356fda56a06dd1bc008d2cd8bb32d791b359eab26457e2f1a65a7ceab78fbf55edd1ba9443b92daae5f3f97cd99edc4c60091fa41c0fbe1c5853dbc1bb67d9def9e39f60f66f994ee1ef47814fd086ac1354e1ca9ce4fe015ea8513ab35322e33a9a14d5d654c6d10cf68f88af81a88d02ca21ce34761f22a540c303c5df598872900e785d7da9e34a0e5f245fe01f528bf28beb6e9c99b76e0e99563554a9c5a50970b61ce15d30263975bec1a733b8ce8ad70aeafd588b589992a7a76b7ef798c5caa594fc95d32f06c6f023fd3d8f0150da1376140a5159b1953cff6cac5b17f5ad11aa2a1a5b46c81837b71f0012dd9dc075f57265cf127aa62fdeb6c046079bd418f06e18b810a50df98884a0993fbb35c00a27c304b94e870af191d3c6069d1bf5c86a1e699c536d3f34569e693c401d0831051f6cda58377e4a200a83550609dc24d2c1042cddcf9cd26fdd6d86d12f846c530a1395c2392c18904ff3020b6b57afaeb023cef42b47eccc863207e3d253f0720eef1cc2981660e390ed430ae8476751648737fad1acd56856cf9631bece0284bfa6c950d0ab0ef1827f913df339a0a55c1d80a5e66c83284c8fbfac6a7e025873813f6b25130ab12e5a9d42b7c1b8fcf85153101995018b672d2682132951e6fba6ee47442785c22e2b3f276905c34dda1442cc811710ef95e09e026b2069c4669e55415a2628fdf1207bd5df51ce2d5f87e7e8c311d48cb79ee0dc6c3a28b1c012cda40a34a03708e3e0fe1154967cbc5712007fd1b32e623a98094e21ec96c6077986a243573e3bd7ecc747f287f4a18c739658682961146e5d0237cf46839dd7656a9ac51e69ff90fc9d9bc4167ddd424578999be1481d70cef68a15d8046525ccd1374c268f1e',
    search_pointer_and_name_query_url: 'https://qa-sef1.pipl.com/search/?q=johnathan+goodwin&sp=97845f13a749e49d9d6c2b6cf32d6716ca1c1dbfb3703f21bd93d48e4fbb9651c58cac686f168b81339e12c0586edb365472a3f2d166e962ad737705c8a0ab858b0eba68ba60cf48df7078f631434229033aa89be04a3807f9e79a399ae257eb63960a5a4d2fc6b4beb62eb6d56d091017427cc8b33af18b3576dbdabc8a7793f3a6003e7899dd57c77c254db56017357dea8d003ff9d8f7d51b9fed5bec518a2ff125416346a1a5ce379a9cff4a578148735fc2c578631cc65781c9fbcdb63fe556d2e636b509722abddd5a07318e04&l=&sloc=&in=6',

    account_is_used_somewhere_else_message: '//*[@id="content"]/h1',

    no_assignment_subs_page: '//*[@id="js-nulluser"]',
    assign_button_assign_subscription_modal:'//div[5]/div/div[2]/div/div/div[3]/button[1]',
    pro_200_new_subscription:'//*[@id="root"]/div/section/div/div[2]/div/div[2]/div/ul/li[1]/div[1]/span',
    logged_user_menu:'//*[@id="js-navbar"]/ul/li[2]/a[2]/span',
    users_email_sub_page2: '//*[@id="root"]/div/section/div/div[2]/div/div[2]/div',
    subscription_page_add_sub_modal_200: '//div[@class=\'row\']/div[@class=\'col-sm-12 col-xs-12\']/div/div[@class=\'c-checkout-payment col-xs-12\']/div[@class=\'c-checkout-payment__explanation\']/div[@class=\'rc-slider-wrapper\']/div[@class=\'rc-slider rc-slider-with-marks\']/div[@class=\'rc-slider-mark\']/span[@class=\'rc-slider-mark-text rc-slider-mark-text-active\']/div[@class=\'slider-text\']',
    subscription_page_add_sub_modal_yearly: '//*[@id="subscription_payment_year"]',
    subscription_page_add_sub_title_text:'/html/body/div[5]/div/div[2]/div/div/div[1]/h4',
    subscription_page_first_subscription:'//*[@id="root"]/div/section/div/div[2]/div/div[2]/div[1]/ul/li[1]',
    subscription_page_first_sub_menu:'//*[@id="root"]/div/section/div/div[2]/div/div[2]/div[1]/ul/li[2]/div[5]/div',
    subscription_page_sub_menu_assign_to_another: '//*[@id="root"]/div/section/div/div[2]/div/div[2]/div[1]/ul/li[2]/div[5]/div/ul/li[1]/a',
    subscription_page_assign_subscription_title:'/html/body/div[5]/div/div[2]/div/div/div[1]/h4',
    subscription_page_assign_menu_assign_to_a_new_user:'/html/body/div[5]/div/div[2]/div/div/div[2]/div[2]/div',
    subscription_page_assign_menu_assign_to_existing:'/html/body/div[5]/div/div[2]/div/div/div[2]/div[3]/div[1]/label',
    subscription_page_assign_menu_assign_to_existing_input:'/html/body/div[5]/div/div[2]/div/div/div[2]/div[3]/div[2]/div/input[1]',
    subscription_page_assign_menu_assign_to_no_one:'/html/body/div[5]/div/div[2]/div/div/div[2]/div[4]/div',
    input_assign_a_new_user_name:'/html/body/div[5]/div/div[2]/div/div/div[2]/div[2]/form/div[1]/span[1]/input',
    input_assign_a_new_user_email:'/html/body/div[5]/div/div[2]/div/div/div[2]/div[2]/form/div[2]/span[1]/input',
    input_assign_a_new_user_password:'/html/body/div[5]/div/div[2]/div/div/div[2]/div[2]/form/div[3]/span[1]/input',
    subscription_page_first_subscription_assignment: '//*[@id="root"]/div/section/div/div[2]/div/div[2]/div/ul/li[1]/div[2]',
    subscription_page_title_text:'//*[@id="root"]/div/section/div/div[2]/div/h3',
    subscription_page_assign_multiple_subscriptions_top_button:'//*[@id="root"]/div/section/div/div[2]/div/h3/div/a[1]',
    assign_multiple_subscriptions_modal_title_text:'/html/body/div[5]/div/div[2]/div/div/div[1]/h4',
    assign_multiple_subscriptions_modal_close_button:'/html/body/div[5]/div/div[2]/div/div/div[3]/button[2]',
    assign_subscription_modal_close_button:'/html/body/div[5]/div/div[2]/div/div/div[3]/button[2]',
    subscription_page_second_user_assignment_name:'//*[@id="root"]/div/section/div/div[2]/div/div[2]/div[1]/ul/li[2]/div[2]',
    assign_subscription_modal_exist_user_menu_random_user:'/html/body/div[5]/div/div[2]/div/div/div[2]/div[3]/div[2]/ul/li[4]/a/span',
    subscription_page_random_user_assignment:'//*[@id="root"]/div/section/div/div[2]/div/div[2]/div[1]/ul/li[6]/div[2]',
    subscription_page_sub_menu_first_change_sub:'//*[@id="root"]/div/section/div/div[2]/div/div[2]/div[1]/ul/li[2]/div[5]/div/ul/li[2]',
    change_subscription_modal_500_searches:'/html/body/div[5]/div/div[2]/div/div/div[2]/div/div/div/div/div[2]/div/div/div[5]/span[2]/div',
    change_subscription_modal_credit_for_exist_sub:'/html/body/div[5]/div/div[2]/div/div/div[2]/div/div/div/div[1]/div[1]/div[2]/div[1]',
    change_subscription_modal_unlimited:'/html/body/div[5]/div/div[2]/div/div/div[2]/div/div/div/div[1]/div[3]/div/div/div[5]/span[3]/div',
    change_subscription_modal_monthly:'/html/body/div[5]/div/div[2]/div/div/div[2]/div/div/div/div[1]/div[4]/div[2]',


};
